export const productConstants ={ 


    CREATE_PRODUCT_REQUEST : 'CREATE_PRODUCT_REQUEST',
    CREATE_PRODUCT_SUCCESS : 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_FAILURE : 'CREATE_PRODUCT_FAILURE',
    
    GET_ALL_PRODUCTS_REQUEST : 'GET_ALL_PRODUCTS_REQUEST',
    GET_ALL_PRODUCTS_SUCCESS : 'GET_ALL_PRODUCTS_SUCCESS',
    GET_ALL_PRODUCTS_FAILURE : 'GET_ALL_PRODUCTS_FAILURE',
    
    GET_PRODUCT_REQUEST : 'GET_PRODUCT_REQUEST',
    GET_PRODUCT_SUCCESS : 'GET_PRODUCT_SUCCESS',
    GET_PRODUCT_FAILURE : 'GET_PRODUCT_FAILURE',
    
    UPDATE_PRODUCT_REQUEST : 'UPDATE_PRODUCT_REQUEST',
    UPDATE_PRODUCT_SUCCESS : 'UPDATE_PRODUCT_SUCCESS',
    UPDATE_PRODUCT_FAILURE : 'UPDATE_PRODUCT_FAILURE',
    
    DELETE_PRODUCT_REQUEST : 'DELETE_PRODUCT_REQUEST',
    DELETE_PRODUCT_SUCCESS : 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILURE : 'DELETE_PRODUCT_FAILURE',
    }

    export const formulaireConstants ={ 


        CREATE_FORMULAIRE_REQUEST : 'CREATE_FORMULAIRE_REQUEST',
        CREATE_FORMULAIRE_SUCCESS : 'CREATE_FORMULAIRE_SUCCESS',
        CREATE_FORMULAIRE_FAILURE : 'CREATE_FORMULAIRE_FAILURE',
        
        GET_ALL_FORMULAIRES_REQUEST : 'GET_ALL_FORMULAIRES_REQUEST',
        GET_ALL_FORMULAIRES_SUCCESS : 'GET_ALL_FORMULAIRES_SUCCESS',
        GET_ALL_FORMULAIRES_FAILURE : 'GET_ALL_FORMULAIRES_FAILURE',
        
        GET_FORMULAIRE_REQUEST : 'GET_FORMULAIRE_REQUEST',
        GET_FORMULAIRE_SUCCESS : 'GET_FORMULAIRE_SUCCESS',
        GET_FORMULAIRE_FAILURE : 'GET_FORMULAIRE_FAILURE',
        
        UPDATE_FORMULAIRE_REQUEST : 'UPDATE_FORMULAIRE_REQUEST',
        UPDATE_FORMULAIRE_SUCCESS : 'UPDATE_FORMULAIRE_SUCCESS',
        UPDATE_FORMULAIRE_FAILURE : 'UPDATE_FORMULAIRE_FAILURE',
        
        DELETE_FORMULAIRE_REQUEST : 'DELETE_FORMULAIRE_REQUEST',
        DELETE_FORMULAIRE_SUCCESS : 'DELETE_FORMULAIRE_SUCCESS',
        DELETE_FORMULAIRE_FAILURE : 'DELETE_FORMULAIRE_FAILURE',
        }

        export const cartConstants = {
            ADD_TO_CART_REQUEST: 'ADD_TO_CART_REQUEST',
            ADD_TO_CART_SUCCESS: 'ADD_TO_CART_SUCCESS',
            ADD_TO_CART_FAILURE: 'ADD_TO_CART_FAILURE',
            GET_CART_REQUEST: 'GET_CART_REQUEST',
            GET_CART_SUCCESS: 'GET_CART_SUCCESS',
            GET_CART_FAILURE: 'GET_CART_FAILURE',
            UPDATE_CART_REQUEST: 'UPDATE_CART_REQUEST',
            UPDATE_CART_SUCCESS: 'UPDATE_CART_SUCCESS',
            UPDATE_CART_FAILURE: 'UPDATE_CART_FAILURE',
            DELETE_CART_REQUEST: 'DELETE_CART_REQUEST',
            DELETE_CART_SUCCESS: 'DELETE_CART_SUCCESS',
            DELETE_CART_FAILURE: 'DELETE_CART_FAILURE'

        }

        export const carttwoConstants = {
            ADD_TO_CARTTWO_REQUEST: 'ADD_TO_CARTTWO_REQUEST',
            ADD_TO_CARTTWO_SUCCESS: 'ADD_TO_CARTTWO_SUCCESS',
            ADD_TO_CARTTWO_FAILURE: 'ADD_TO_CARTTWO_FAILURE',
            GET_CARTTWO_REQUEST: 'GET_CARTTWO_REQUEST',
            GET_CARTTWO_SUCCESS: 'GET_CARTTWO_SUCCESS',
            GET_CARTTWO_FAILURE: 'GET_CARTTWO_FAILURE',
            UPDATE_CARTTWO_REQUEST: 'UPDATE_CARTTWO_REQUEST',
            UPDATE_CARTTWO_SUCCESS: 'UPDATE_CARTTWO_SUCCESS',
            UPDATE_CARTTWO_FAILURE: 'UPDATE_CARTTWO_FAILURE',
            REMOVE_ITEM_FROM_CART_REQUEST: 'REMOVE_ITEM_FROM_CART_REQUEST',
            REMOVE_ITEM_FROM_CART_SUCCESS: 'REMOVE_ITEM_FROM_CART_SUCCESS',
            REMOVE_ITEM_FROM_CART_FAILURE: 'REMOVE_ITEM_FROM_CART_FAILURE',
            UPDATE_ITEM_QUANTITY_REQUEST: 'UPDATE_ITEM_QUANTITY_REQUEST',
            UPDATE_ITEM_QUANTITY_SUCCESS: 'UPDATE_ITEM_QUANTITY_SUCCESS',
            UPDATE_ITEM_QUANTITY_FAILURE: 'UPDATE_ITEM_QUANTITY_FAILURE',
            CLEAR_CART: 'CLEAR_CART' ,
            NEW_CART_CREATED: 'NEW_CART_CREATED' ,
            GET_ALL_CARTS_REQUEST: 'GET_ALL_CARTS_REQUEST',
            GET_ALL_CARTS_SUCCESS: 'GET_ALL_CARTS_SUCCESS',
            GET_ALL_CARTS_FAILURE: 'GET_ALL_CARTS_FAILURE',
        
        }


        export const  carouselConstants ={ 


            CREATE_CAROUSEL_REQUEST : 'CREATE_CAROUSEL_REQUEST',
            CREATE_CAROUSEL_SUCCESS : 'CREATE_CAROUSEL_SUCCESS',
            CREATE_CAROUSEL_FAILURE : 'CREATE_CAROUSEL_FAILURE',
            
            GET_ALL_CAROUSELS_REQUEST : 'GET_ALL_CAROUSELS_REQUEST',
            GET_ALL_CAROUSELS_SUCCESS : 'GET_ALL_CAROUSELS_SUCCESS',
            GET_ALL_CAROUSELS_FAILURE : 'GET_ALL_CAROUSELS_FAILURE',
            
            GET_CAROUSEL_REQUEST : 'GET_CAROUSEL_REQUEST',
            GET_CAROUSEL_SUCCESS : 'GET_CAROUSEL_SUCCESS',
            GET_CAROUSEL_FAILURE : 'GET_CAROUSEL_FAILURE',
            
            UPDATE_CAROUSEL_REQUEST : 'UPDATE_CAROUSEL_REQUEST',
            UPDATE_CAROUSEL_SUCCESS : 'UPDATE_CAROUSEL_SUCCESS',
            UPDATE_CAROUSEL_FAILURE : 'UPDATE_CAROUSEL_FAILURE',
            
            DELETE_CAROUSEL_REQUEST : 'DELETE_CAROUSEL_REQUEST',
            DELETE_CAROUSEL_SUCCESS : 'DELETE_CAROUSEL_SUCCESS',
            DELETE_CAROUSEL_FAILURE : 'DELETE_CAROUSEL_FAILURE',
            }

            export const  catalogueConstants ={ 


                CREATE_CATALOGUE_REQUEST : 'CREATE_CATALOGUE_REQUEST',
                CREATE_CATALOGUE_SUCCESS : 'CREATE_CATALOGUE_SUCCESS',
                CREATE_CATALOGUE_FAILURE : 'CREATE_CATALOGUE_FAILURE',
                
                GET_ALL_CATALOGUES_REQUEST : 'GET_ALL_CATALOGUES_REQUEST',
                GET_ALL_CATALOGUES_SUCCESS : 'GET_ALL_CATALOGUES_SUCCESS',
                GET_ALL_CATALOGUES_FAILURE : 'GET_ALL_CATALOGUES_FAILURE',
                
                GET_CATALOGUE_REQUEST : 'GET_CATALOGUE_REQUEST',
                GET_CATALOGUE_SUCCESS : 'GET_CATALOGUE_SUCCESS',
                GET_CATALOGUE_FAILURE : 'GET_CATALOGUE_FAILURE',
                
                UPDATE_CATALOGUE_REQUEST : 'UPDATE_CATALOGUE_REQUEST',
                UPDATE_CATALOGUE_SUCCESS : 'UPDATE_CATALOGUE_SUCCESS',
                UPDATE_CATALOGUE_FAILURE : 'UPDATE_CATALOGUE_FAILURE',
                
                DELETE_CATALOGUE_REQUEST : 'DELETE_CATALOGUE_REQUEST',
                DELETE_CATALOGUE_SUCCESS : 'DELETE_CATALOGUE_SUCCESS',
                DELETE_CATALOGUE_FAILURE : 'DELETE_CATALOGUE_FAILURE',
                }

                export const  aboutConstants ={ 


                    CREATE_ABOUT_REQUEST : 'CREATE_ABOUT_REQUEST',
                    CREATE_ABOUT_SUCCESS : 'CREATE_ABOUT_SUCCESS',
                    CREATE_ABOUT_FAILURE : 'CREATE_ABOUT_FAILURE',
                    
                    GET_ALL_ABOUTS_REQUEST : 'GET_ALL_ABOUTS_REQUEST',
                    GET_ALL_ABOUTS_SUCCESS : 'GET_ALL_ABOUTS_SUCCESS',
                    GET_ALL_ABOUTS_FAILURE : 'GET_ALL_ABOUTS_FAILURE',
                    
                    GET_ABOUT_REQUEST : 'GET_ABOUT_REQUEST',
                    GET_ABOUT_SUCCESS : 'GET_ABOUT_SUCCESS',
                    GET_ABOUT_FAILURE : 'GET_ABOUT_FAILURE',
                    
                    UPDATE_ABOUT_REQUEST : 'UPDATE_ABOUT_REQUEST',
                    UPDATE_ABOUT_SUCCESS : 'UPDATE_ABOUT_SUCCESS',
                    UPDATE_ABOUT_FAILURE : 'UPDATE_ABOUT_FAILURE',
                    
                    DELETE_ABOUT_REQUEST : 'DELETE_ABOUT_REQUEST',
                    DELETE_ABOUT_SUCCESS : 'DELETE_ABOUT_SUCCESS',
                    DELETE_ABOUT_FAILURE : 'DELETE_ABOUT_FAILURE',
                    }